//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriorityLifeMacro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriorityLifeMacro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;pattern.macro.project version=&quot;1.0.0.0&quot;&gt;
        ///  &lt;pattern name=&quot;americo&quot;&gt;
        ///     &lt;item&gt;/AMERICO.txt&lt;/item&gt;
        ///     &lt;item&gt;.csv&lt;/item&gt;
        ///     &lt;item&gt;cr&lt;/item&gt;
        ///     &lt;item&gt;AMERICO/&lt;/item&gt;
        ///     &lt;item&gt;300000&lt;/item&gt;
        ///  &lt;/pattern&gt;
        ///  &lt;pattern name=&quot;moo&quot;&gt;
        ///     &lt;item&gt;/MOO.iim&lt;/item&gt;
        ///     &lt;item&gt;.xls&lt;/item&gt;
        ///     &lt;item&gt;ie&lt;/item&gt;
        ///     &lt;item&gt;MOO/&lt;/item&gt;
        ///     &lt;item&gt;300000&lt;/item&gt;
        ///  &lt;/pattern&gt;
        ///  &lt;pattern name=&quot;aig&quot;&gt;
        ///     &lt;item&gt;/AIG.iim&lt;/item&gt;
        ///     &lt;item&gt;.xlsx&lt;/item&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string macro_pattern_version_1_0 {
            get {
                return ResourceManager.GetString("macro_pattern_version_1_0", resourceCulture);
            }
        }
    }
}
