//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriorityLifeDataLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriorityLifeDataLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;pattern.excel.project version=&quot;1.0.0.0&quot;&gt;
        ///  &lt;pattern name=&quot;aig&quot;&gt;
        ///    &lt;extension&gt;xlsx&lt;/extension&gt;
        ///    &lt;dltype&gt;bulk&lt;/dltype&gt;
        ///    &lt;tableline&gt;5&lt;/tableline&gt;
        ///    &lt;columns&gt;
        ///      &lt;column&gt;
        ///		&lt;name cl=&quot;agent_name&quot;&gt;Writing/Servicing Agent&lt;/name&gt;
        ///		  &lt;dont_item&gt;agent name not found&lt;/dont_item&gt;
        ///        &lt;dont_item&gt;_blank&lt;/dont_item&gt;
        ///	  &lt;/column&gt;
        ///      &lt;column&gt;
        ///		    &lt;name cl=&quot;amount&quot;&gt;Premium&lt;/name&gt;
        ///        &lt;dont_item&gt;_blank&lt;/dont_item&gt;
        ///      &lt;/column [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string excel_pattern_version_1_0 {
            get {
                return ResourceManager.GetString("excel_pattern_version_1_0", resourceCulture);
            }
        }
    }
}
